name: lecturecv-ex02
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.8
  
  # Jupyter and IPython
  - jupyter
  - ipykernel
  - ipython
  - ipywidgets
  - ipympl
  - notebook
  - nb_conda_kernels
  
  # Scientific computing
  - numpy>=1.20
  - scipy>=1.6
  - matplotlib>=3.3
  - pillow>=8.2
  - scikit-image>=0.18
  
  # PyTorch - will automatically select appropriate version for platform
  - pytorch>=1.8
  - torchvision>=0.9
  - torchaudio>=0.8
  
  # Image processing
  - imageio
  - pywavelets
  - tifffile
  
  # Other utilities
  - pyyaml
  - cloudpickle
  - networkx
  - dask-core
  - cytoolz
  - toolz
  - fsspec
  - partd
  - locket
  
  # Pip packages
  - pip
  - pip:
    - opencv-python>=4.5.1
